apiVersion: v1
kind: ReplicationController
metadata:
  name: pgwatch2
  annotations:
    description: "All-in-one pgwatch2 image - https://github.com/cybertec-postgresql/pgwatch2"
spec:
  replicas: 1
  selector:
    app: pgwatch2
  template:
    metadata:
      name: pgwatch2
      labels:
        app: pgwatch2
    spec:
      containers:
      - image: cybertec/pgwatch2-openshift
        name: master
        ports:
          - containerPort: 3000
            protocol: TCP
          - containerPort: 5432
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8086
            protocol: TCP
          - containerPort: 8088
            protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /var/lib/postgresql
            name: pgwatch2-postgresql
          - mountPath: /var/lib/grafana
            name: pgwatch2-grafana
          - mountPath: /var/lib/influxdb
            name: pgwatch2-influx
      volumes:
      - name: pgwatch2-postgresql
        persistentVolumeClaim:
          claimName: pgwatch2-postgresql
      - name: pgwatch2-grafana
        persistentVolumeClaim:
          claimName: pgwatch2-grafana
      - name: pgwatch2-influx
        persistentVolumeClaim:
          claimName: pgwatch2-influx
      restartPolicy: Always
