services:
  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9187:9187
    restart: unless-stopped
    volumes:
      - "./bootstrap/prometheus.yml:/etc/prometheus/prometheus.yml"
    depends_on:
      postgres:
        condition: service_healthy